// utlis/blogData.tsx
import BlogImage1 from "@/assets/images/Blog1.jpg";
import BlogImage2 from "@/assets/images/Blog2.jpg";
import BlogImage3 from "@/assets/images/Blog3.jpg";

export const blogData = [
  {
    id: 1,
    mainCategory: "Blog",
    category: "Business",
    image: BlogImage1,
    heading: "A new type of chart — Session volume profile",
    description:
      "The chart shows volume histograms for the specified sessions, sub-sessions, or time intervals set in the settings.",
    date: "2024-09-16", 
    author: "John Doe", 
    comments: 15,
    likes: 50, 
  },
  { 
    id: 2,
    mainCategory: "Blog",
    category: "Charting",
    image: BlogImage2,
    heading: "Empowering the financial education with UFABC",
    description:
      "Founded in 2005, UFABC initially offered the Bachelor in Science and Technology program.",
    date: "2024-09-10",
    author: "John Doe", 
    comments: 1,
    likes: 0, 
  },
  {
    id: 3,
    mainCategory: "Blog",
    category: "Charting",
    image: BlogImage3,
    heading: "Synchronized bar replay",
    description:
      "And we’re finally ready to present you the long-awaited feature — a synchronized Bar Replay!",
    date: "2024-09-14",
    author: "John Doe", 
    comments: 5,
    likes: 5, 
  },
  {
    id: 4,
    mainCategory: "Blog",
    category: "Business",
    image: BlogImage1,
    heading: "Introducing Trade nation, a new broker on Epochfin",
    description:
      "Welcome Trade Nation, a newly integrated broker within the TradingView  trading ecosystem. Access CFD and spread trading on 1,000+ markets.",
    date: "2024-08-31",
    author: "John Doe", 
    comments: 10,
    likes: 2, 
  },
  {
    id: 5,
    mainCategory: "Blog",
    category: "Screeners",
    image: BlogImage2,
    heading: "Welcoming ThinkMarkets: new brokerage on TradingView",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-10",
    author: "John Doe", 
    comments: 1,
    likes: 9, 
  },
  {
    id: 6,
    mainCategory: "Blog",
    category: "Brokerage",
    image: BlogImage3,
    heading: "Introducing moomoo: new broker on TradingView",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-05",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
  {
    id: 7,
    mainCategory: "Blog",
    category: "Screeners",
    image: BlogImage1,
    heading: "Introducing moomoo: new broker on TradingView",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-24",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
  {
    id: 8,
    mainCategory: "Blog",
    category: "Mobile",
    image: BlogImage2,
    heading: "Display visuals on the chart from your pane scripts",
    description: "To bring markets closer to your desktops, we’ve expanded our trading  offerings and added one more valuable partner to the brokers’ list.",
    date: "2024-08-24",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
  {
    id: 9,
    mainCategory: "Blog",
    category: "Trade and brokerage",
    image: BlogImage2,
    heading: "The Leap is back with 250 cash prizes to win",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-24",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
  {
    id: 10,
    mainCategory: "Community",
    category: "Editors’ picks",
    image: BlogImage1,
    heading: "A new type of chart — Session volume profile",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-31", 
    author: "John Doe", 
    comments: 15,
    likes: 50, 
  },
  { 
    id:11,
    mainCategory: "Community",
    category: "Stocks",
    image: BlogImage2,
    heading: "Empowering the financial education with UFABC",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-31",
    author: "John Doe", 
    comments: 1,
    likes: 0, 
  },
  {
    id: 12,
    mainCategory: "Community",
    category: "Crypto",
    image: BlogImage3,
    heading: "Synchronized bar replay",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-31",
    author: "John Doe", 
    comments: 5,
    likes: 5, 
  },
  {
    id: 13,
    mainCategory: "Community",
    category: "Forex",
    image: BlogImage1,
    heading: "Introducing Trade nation, a new broker on Epochfin",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-31",
    author: "John Doe", 
    comments: 10,
    likes: 2, 
  },
  {
    id: 14,
    mainCategory: "Community",
    category: "Indices",
    image: BlogImage2,
    heading: "Welcoming ThinkMarkets: new brokerage on TradingView",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-10",
    author: "John Doe", 
    comments: 1, 
    likes: 9, 
  },
  {
    id: 15,
    mainCategory: "Community",
    category: "Futures",
    image: BlogImage3,
    heading: "Introducing moomoo: new broker on TradingView",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-05",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
  {
    id: 16,
    mainCategory: "Community",
    category: "Popular",
    image: BlogImage1,
    heading: "Introducing moomoo: new broker on TradingView",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-24",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
  {
    id: 17,
    mainCategory: "Community",
    category: "Recent",
    image: BlogImage2,
    heading: "Display visuals on the chart from your pane scripts",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-24",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
  {
    id: 18,
    mainCategory: "Community",
    category: "Editors’ picks",
    image: BlogImage2,
    heading: "The Leap is back with 250 cash prizes to win",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    date: "2024-08-24",
    author: "John Doe", 
    comments: 9,
    likes: 8, 
  },
];
