'use client';
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { usePathname } from "next/navigation";
import Footer from "@/components/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  backgroundClass = "",
}: Readonly<{
  children: React.ReactNode;
  backgroundClass?: string;
}>) {
  const pathname = usePathname();
  
  // Determine background class based on pathname or other logic
  const bodyClass = pathname === "/" 
    ? "black-background" 
    : pathname === "/get-started"
    ? "black-background"
    : "white-background";
  
  return (
    <html lang="en">
      <body className={`${bodyClass} ${backgroundClass}`}>
        <Header />
        <main className="pt-[82px]">
           {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
