import { ReactNode } from 'react';
import type { Metadata } from "next";
import "./globals.css";
import ClientRootLayout from '../RootLayout/ClientRootLayout'; 
import localFont from "next/font/local";

const HelveticaNeueThin = localFont({
  src: '../assets/fonts/HelveticaNeueThin.otf',
  display: 'swap',
  variable: '--font-HelveticaNeueThin',
});
const HelveticaNeue = localFont({
  src: '../assets/fonts/HelveticaNeueRoman.otf',
  display: 'swap',
  variable: '--font-HelveticaNeue',
});
const HelveticaNeueMedium = localFont({
  src: '../assets/fonts/HelveticaNeueMedium.otf',
  display: 'swap',
  variable: '--font-HelveticaNeueMedium',
}); 
const PublicSansBlack = localFont({
  src: '../assets/fonts/PublicSans-Black.ttf',
  display: 'swap',
  variable: '--font-PublicSansBlack',
}); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({  
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className=''>
      <body id='black-background' className={`${HelveticaNeueThin.variable} ${HelveticaNeue.variable} ${HelveticaNeueMedium.variable} ${PublicSansBlack.variable}`}>  
        <ClientRootLayout>
          {children}
        </ClientRootLayout>     
      </body>
    </html>
  );
}
