import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import ClientRootLayout from "../RootLayout/ClientRootLayout";
import localFont from "next/font/local";
import { EpochGPTIcon } from "@/utlis/svg";
import Link from "next/link";

const HelveticaNeueThin = localFont({
  src: "../assets/fonts/HelveticaNeueThin.otf",
  display: "swap",
  variable: "--font-HelveticaNeueThin",
});
const HelveticaNeue = localFont({
  src: "../assets/fonts/HelveticaNeueRoman.otf",
  display: "swap",
  variable: "--font-HelveticaNeue",
});
const HelveticaNeueMedium = localFont({
  src: "../assets/fonts/HelveticaNeueMedium.otf",
  display: "swap",
  variable: "--font-HelveticaNeueMedium",
});
const PublicSansBlack = localFont({
  src: "../assets/fonts/PublicSans-Black.ttf",
  display: "swap",
  variable: "--font-PublicSansBlack",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        id="black-background"
        className={`${HelveticaNeueThin.variable} ${HelveticaNeue.variable} ${HelveticaNeueMedium.variable} ${PublicSansBlack.variable}`}
      >
        <ClientRootLayout>{children}</ClientRootLayout>

        <div className="epoch-button fixed z-[7] bottom-10 left-1/2 transform -translate-x-1/2 md:left-auto md:-translate-x-0 md:bottom-16 md:right-16">
          <Link className="button-black !px-[20px] " href="#">
            <EpochGPTIcon />
            Ask EpochGPT
          </Link>
        </div>

      </body>
    </html>
  );
}
